ALTER TABLE "outlets"
ADD COLUMN "telepon" VARCHAR(30),
ADD COLUMN "timezone" VARCHAR(50) NOT NULL DEFAULT 'Asia/Jakarta',
ADD COLUMN "currency" VARCHAR(3) NOT NULL DEFAULT 'IDR',
ADD COLUMN "tax_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN "print_receipt_auto" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "low_stock_alert" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "daily_whatsapp_report" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "auto_tax" BOOLEAN NOT NULL DEFAULT false;
